// Main library entry point — everything consumers import from "the-old-ui"

// UI Components (clean names, no Ph prefix)
export {
  Button,
  ButtonChrome,
  Alert,
  Badge,
  Card,
  Drawer,
  Kbd,
  DropdownButton,
  DropdownItem,
  DropdownMenu,
  Checkbox,
  FileUpload,
  Input,
  Radio,
  Range,
  Select,
  Textarea,
  Toggle,
  Modal,
  Breadcrumbs,
  Pagination,
  Panel,
  Rating,
  SearchGroup,
  SearchInput,
  Table,
  Stat,
  Toast,
  ToastStack,
  Tabs,
  Avatar,
  AvatarGroup,
  Progress,
  ChatBubble,
  Terminal,
  Indicator,
  Timeline,
  Display,
  H1,
  H2,
  H3,
  H4,
  H5,
  P,
  Small,
  Caption,
  Overline,
  Lead,
  Mono,
  Label,
  Accordion,
  Stepper,
  SegmentedControl,
  CommandPalette,
  Calendar,
  HoverCard,
  EmptyState,
  FilterChips,
  CodeBlock,
  ThemeDomSync,
  ThemeManager,
  ThemeSwitcher,
  Icon,
  IconByName,
  CollapsibleSection,
  ComponentDocs,
  ShowcaseWrapper,
} from "@/components/ui";

// Type exports (clean names)
export type {
  ButtonProps,
  ButtonShape,
  ButtonSize,
  ButtonVariant,
  ButtonChromeProps,
  AlertProps,
  AlertStatus,
  BadgeProps,
  BadgeSize,
  BadgeVariant,
  CardProps,
  CardVariant,
  DrawerProps,
  DrawerSide,
  DrawerSize,
  KbdProps,
  KbdVariant,
  DropdownAlign,
  DropdownButtonProps,
  DropdownMenuProps,
  CheckboxProps,
  FileUploadProps,
  InputProps,
  InputSize,
  InputVariant,
  RadioProps,
  RangeProps,
  SelectProps,
  TextareaProps,
  ToggleProps,
  ModalProps,
  ModalSize,
  BreadcrumbItem,
  BreadcrumbsProps,
  PaginationProps,
  PanelProps,
  RatingProps,
  SearchGroupProps,
  SearchInputProps,
  TableColumn,
  TableProps,
  StatProps,
  StatTone,
  ToastProps,
  ToastStackProps,
  ToastStatus,
  TabItem,
  TabsProps,
  TabsVariant,
  AvatarProps,
  AvatarSize,
  AvatarStatus,
  AvatarGroupProps,
  ProgressProps,
  ChatBubbleProps,
  ChatBubbleVariant,
  TerminalProps,
  IndicatorProps,
  IndicatorPosition,
  TimelineProps,
  TimelineEvent,
  IconProps,
  IconName,
  ThemeManagerProps,
  ThemeSwitcherProps,
  ComponentDocsProps,
  ComponentPropRow,
} from "@/components/ui";

// Themes
export type { ThemeDefinition, ThemeId } from "@/themes/types";
export { DEFAULT_THEME_ID, THEMES, THEME_GROUPS, getTheme, isThemeId } from "@/themes/registry";
export { persistTheme, readStoredTheme, THEME_INIT_SCRIPT } from "@/themes/init-theme";

// Charts
export {
  HogTrendLineChart,
  InsightDoughnutChart,
  InsightHorizontalBarChart,
  InsightPolarAreaChart,
  InsightStackedBarChart,
  InsightVerticalBarChart,
} from "@/components/charts";

// Dashboard primitives
export {
  DashboardWell,
  DashboardToolbar,
  DashboardGrid,
  DashboardFiltersBar,
  DashboardKpiCard,
  DashboardInsightPlaceholder,
  InsightShell,
  InsightShellHeader,
  MiniTrendBars,
  InsightMiniCard,
} from "@/components/dashboard";
export type {
  DashboardWellProps,
  DashboardToolbarProps,
  DashboardGridProps,
  DashboardKpiCardProps,
  DashboardInsightPlaceholderProps,
  InsightShellProps,
  InsightShellHeaderProps,
  MiniTrendBarsProps,
  InsightMiniCardProps,
} from "@/components/dashboard";

// Tailwind preset — import directly from "the-old-ui/tailwind-preset"

// All icons
export * from "@/components/icons";
