// Main library entry — product surface for ShellStack apps.
"use client";

export {
  Button,
  ButtonChrome,
  Alert,
  Badge,
  Card,
  Loader,
  LoadingState,
  Skeleton,
  AuthCard,
  AuthDivider,
  AuthLayout,
  SettingsLayout,
  SettingsNav,
  DropdownButton,
  DropdownItem,
  DropdownMenu,
  DropdownRadioGroup,
  DropdownRadioItem,
  Checkbox,
  FileUpload,
  Input,
  Radio,
  Select,
  Textarea,
  Toggle,
  FormField,
  Modal,
  Panel,
  SearchInput,
  Table,
  Stat,
  Avatar,
  AvatarGroup,
  Progress,
  Display,
  SectionTitle,
  H1,
  H2,
  H3,
  H4,
  H5,
  P,
  Small,
  Caption,
  Overline,
  Lead,
  Mono,
  Label,
  Accordion,
  SegmentedControl,
  CommandPalette,
  Calendar,
  Tooltip,
  TooltipProvider,
  EmptyState,
  FilterChips,
  FilterBar,
  FilterMenu,
  SortMenu,
  Icon,
  IconByName,
  Link,
  Spinner,
  Dot,
  Chip,
} from "@/components/ui";

export type {
  ButtonProps,
  ButtonShape,
  ButtonSize,
  ButtonVariant,
  ButtonChromeProps,
  AlertProps,
  AlertStatus,
  BadgeProps,
  BadgeSize,
  BadgeVariant,
  CardProps,
  CardVariant,
  LoaderProps,
  LoaderSize,
  LoaderVariant,
  LoadingStateProps,
  SkeletonProps,
  SkeletonShape,
  AuthCardProps,
  AuthDividerProps,
  AuthLayoutProps,
  SettingsLayoutProps,
  SettingsNavGroup,
  SettingsNavItem,
  SettingsNavProps,
  DropdownAlign,
  DropdownButtonProps,
  DropdownItemProps,
  DropdownMenuProps,
  DropdownRadioGroupProps,
  DropdownRadioItemProps,
  DropdownSide,
  CheckboxProps,
  FileUploadProps,
  InputProps,
  InputSize,
  InputVariant,
  RadioProps,
  SelectProps,
  TextareaProps,
  ToggleProps,
  FormFieldControlProps,
  FormFieldProps,
  ModalProps,
  ModalSize,
  PanelProps,
  SearchInputProps,
  TableColumn,
  TableProps,
  StatProps,
  StatTone,
  AvatarProps,
  AvatarSize,
  AvatarStatus,
  AvatarGroupProps,
  ProgressProps,
  IconProps,
  CanonicalIconName,
  IconAliasName,
  IconName,
  FilterChip,
  FilterChipsProps,
  FilterBarProps,
  FilterMenuOption,
  FilterMenuProps,
  SortMenuProps,
  TooltipAlign,
  TooltipProps,
  TooltipProviderProps,
  TooltipSide,
  LinkProps,
  SpinnerProps,
  DotProps,
  ChipProps,
} from "@/components/ui";

// Themes
export type { ThemeDefinition, ThemeId } from "@/themes/types";
export {
  DEFAULT_THEME_ID,
  THEMES,
  THEME_GROUPS,
  getTheme,
  isThemeId,
} from "@/themes/registry";
export {
  persistTheme,
  readStoredTheme,
  THEME_INIT_SCRIPT,
} from "@/themes/init-theme";

// Icons
export * from "@/components/icons";
