// Main library entry point — everything consumers import from "the-old-ui"

// UI Components (clean names, no Ph prefix)
"use client";

export {
  Button,
  ButtonChrome,
  Alert,
  Badge,
  Card,
  Drawer,
  Kbd,
  Loader,
  LoadingState,
  Skeleton,
  AuthCard,
  AuthDivider,
  AuthLayout,
  SettingsLayout,
  SettingsNav,
  DropdownButton,
  DropdownItem,
  DropdownMenu,
  DropdownRadioGroup,
  DropdownRadioItem,
  Checkbox,
  FileUpload,
  Input,
  Radio,
  Range,
  Select,
  Textarea,
  Toggle,
  FormField,
  Modal,
  Breadcrumbs,
  Pagination,
  Panel,
  Rating,
  SearchGroup,
  SearchInput,
  Table,
  Stat,
  Toast,
  ToastStack,
  Tabs,
  Avatar,
  AvatarGroup,
  Progress,
  ChatBubble,
  Terminal,
  Indicator,
  Timeline,
  Display,
  H1,
  H2,
  H3,
  H4,
  H5,
  P,
  Small,
  Caption,
  Overline,
  Lead,
  Mono,
  Label,
  Accordion,
  Stepper,
  SegmentedControl,
  CommandPalette,
  Calendar,
  HoverCard,
  Tooltip,
  TooltipProvider,
  EmptyState,
  FilterChips,
  FilterBar,
  FilterMenu,
  SortMenu,
  FilterControls,
  CodeBlock,
  ThemeDomSync,
  ThemeManager,
  ThemeSwitcher,
  Icon,
  IconByName,
  CollapsibleSection,
  ComponentDocs,
  ShowcaseWrapper,
  Banner,
  Dialog,
  Divider,
  Tag,
  ProgressCircle,
  Row,
  Widget,
  Lettermark,
  Splotch,
  Popover,
  LoadingBar,
  Link,
  Spinner,
  Snack,
  Combobox,
  Autocomplete,
  ContextMenu,
  Resizable,
  ScrollArea,
  NumberField,
  InputGroup,
  ButtonGroup,
  ToggleButton,
  ToggleGroup,
  Menubar,
  AlertDialog,
  Dot,
  Collapsible,
  Metric,
  Chip,
  DataTable,
  DatePicker,
} from "@/components/ui";

// Type exports (clean names)
export type {
  ButtonProps,
  ButtonShape,
  ButtonSize,
  ButtonVariant,
  ButtonChromeProps,
  AlertProps,
  AlertStatus,
  BadgeProps,
  BadgeSize,
  BadgeVariant,
  CardProps,
  CardVariant,
  DrawerProps,
  DrawerSide,
  DrawerSize,
  KbdProps,
  KbdPlatform,
  KbdVariant,
  LoaderProps,
  LoaderSize,
  LoaderVariant,
  LoadingStateProps,
  SkeletonProps,
  SkeletonShape,
  AuthCardProps,
  AuthDividerProps,
  AuthLayoutProps,
  SettingsLayoutProps,
  SettingsNavGroup,
  SettingsNavItem,
  SettingsNavProps,
  DropdownAlign,
  DropdownButtonProps,
  DropdownItemProps,
  DropdownMenuProps,
  DropdownRadioGroupProps,
  DropdownRadioItemProps,
  DropdownSide,
  CheckboxProps,
  FileUploadProps,
  InputProps,
  InputSize,
  InputVariant,
  RadioProps,
  RangeProps,
  SelectProps,
  TextareaProps,
  ToggleProps,
  FormFieldControlProps,
  FormFieldProps,
  ModalProps,
  ModalSize,
  BreadcrumbItem,
  BreadcrumbsProps,
  PaginationProps,
  PanelProps,
  RatingProps,
  SearchGroupProps,
  SearchInputProps,
  TableColumn,
  TableProps,
  StatProps,
  StatTone,
  ToastProps,
  ToastStackProps,
  ToastStatus,
  TabItem,
  TabsProps,
  TabsVariant,
  AvatarProps,
  AvatarSize,
  AvatarStatus,
  AvatarGroupProps,
  ProgressProps,
  ChatBubbleProps,
  ChatBubbleVariant,
  TerminalProps,
  IndicatorProps,
  IndicatorPosition,
  TimelineProps,
  TimelineEvent,
  IconProps,
  CanonicalIconName,
  IconAliasName,
  IconName,
  ThemeManagerProps,
  ThemeSwitcherProps,
  ComponentDocsProps,
  ComponentPropRow,
  FilterChip,
  FilterChipsProps,
  FilterBarProps,
  FilterMenuOption,
  FilterMenuProps,
  SortMenuProps,
  FilterControlsProps,
  TooltipAlign,
  TooltipProps,
  TooltipProviderProps,
  TooltipSide,
  BannerProps,
  BannerType,
  DialogProps,
  DividerProps,
  TagProps,
  TagType,
  ProgressCircleProps,
  RowProps,
  WidgetProps,
  LettermarkProps,
  SplotchProps,
  SplotchColor,
  PopoverProps,
  LoadingBarProps,
  LinkProps,
  SpinnerProps,
  SnackProps,
  ComboboxProps,
  ComboboxOption,
  AutocompleteProps,
  AutocompleteOption,
  ContextMenuProps,
  ContextMenuItem,
  ResizableProps,
  ScrollAreaProps,
  NumberFieldProps,
  InputGroupProps,
  ButtonGroupProps,
  ToggleButtonProps,
  ToggleGroupProps,
  MenubarProps,
  MenubarItem,
  AlertDialogProps,
  DotProps,
  CollapsibleProps,
  MetricProps,
  ChipProps,
  DataTableProps,
  DataTableColumn,
  DatePickerProps,
  AppLayoutProps,
  SidebarProps,
  SidebarGroup,
  SidebarItemDef,
} from "@/components/ui";

export { AppLayout, Sidebar } from "@/components/ui";

// Themes
export type { ThemeDefinition, ThemeId } from "@/themes/types";
export {
  DEFAULT_THEME_ID,
  THEMES,
  THEME_GROUPS,
  getTheme,
  isThemeId,
} from "@/themes/registry";
export {
  persistTheme,
  readStoredTheme,
  THEME_INIT_SCRIPT,
} from "@/themes/init-theme";

// Quill-style charts (replaces old Chart.js)
export {
  TimeSeriesLineChart,
  BarChart,
  PieChart,
  Sparkline,
  MetricCard,
  FunnelChart,
} from "@/components/charts";
export type {
  TimeSeriesLineChartProps,
  TimeSeriesLineChartSeries,
  BarChartProps,
  BarChartSeries,
  PieChartProps,
  PieChartSlice,
  SparklineProps,
  MetricCardProps,
  FunnelChartProps,
  FunnelStep,
} from "@/components/charts";



// Tailwind preset — import directly from "the-old-ui/tailwind-preset"

// All icons
export * from "@/components/icons";
